# -*- coding: utf-8 -*-
"""__name__==__main__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMS7IKmI-idess0U9iQ5HpLFwE_POnF4

The if _name_ == "_main_" idiom is a common pattern used in Python scripts to determine whether the script is being run directly or being imported as a module into another script.
In Python, the _name_ variable is a built-in variable that is automatically set to the name of the current module. When a Python script is run directly, the _name_ variable is set to the string _main. When the script is imported as a module into another script, the __name_ variable is set to the name of the module.
"""

#Here's an example of how the if _name_ == "_main_" idiom can be used:
def main():
  #code to run when the script is run directly
  print("Running Script directly")

if __name__ == "__main__":
  main()

# This is useful if you have code that you want to reuse in multiple scripts,but you
#only want it to run when the script is run directly and not when it's imported as a
#module.