# -*- coding: utf-8 -*-
"""Async I/O .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1i9vST_N2e2TgYBmkkHHHmMGl40trRa

**Async I/O**

Also termed as sync for short,is a programming pattern that allows for high-performance I/O operations in a concurrent and non-blocking manner.In Python,async programming is achieved through the use of the asyncio module and asynchoronous functions.It is specially made for I/O bound tasks.I/O-bound tasks—such as making web API calls, querying databases, or reading/writing files—where your program spends most of its time waiting for external responses.

asyncio allows it to switch to another task while waiting for the first one to finish.
"""

# Install nest_asyncio to allow asyncio.run() in an already running event loop environment (like Colab).
!pip install -qqq nest_asyncio

# Apply nest_asyncio to patch asyncio, allowing nested event loops.
import nest_asyncio
nest_asyncio.apply()

# Example
import asyncio
async def my_async_function():
  # asynchronous code here
  await asyncio.sleep(1)
  return "Hello,Async World!!"

async def main():
  result = await my_async_function()
  print(result)

asyncio.run(main())