# -*- coding: utf-8 -*-
"""Creating_Command_line_Utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VETcLxjUlebHbX-3XCu2E7wFB23-oi1C

**Command Line Utility:**(or command line tool)

 It is a text-based program that allows users to perform system tasks, manage files, and automate processes by typing commands into a terminal or console, rather than using a graphical user interface (GUI).In Python,we can create our own command line utilities using the built in argparse module.
"""

#Example
import argparse
parser = argparse.ArgumentParser()
#Adding command line arguments
parser.add_argument("arg1",help="description of first argument")
parser.add_argument("arg2",help="description of second argument")
#parse the arguments
args = parser.parse_args()
#use the arguments in your code
print(args.arg1)
print(args.arg2)
#We need to run it in shell

#Adding an optional argument
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-o ","--optional","--arg1",help="description of first argument",default="default value")
parser.add_argument("--arg2",help="description of second argument",default="default value")
args = parser.parse_args()
print(args.arg1)