# -*- coding: utf-8 -*-
"""File_I/O.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5alSiJc7Jw_OjgrkHVHe-llgdV4NQKl
"""

# opening a file
# Python provides the open() function to open
#a file.It takes two arguments:the name of
#the file and the mode in which the file
#should be opened.The mode can be 'r' for
#reading,'w' for writing,or'a'for appending.

f=open('myfile.txt','r')
#By default,the open() function returns a
#file object that can be used to read from
#or write to the file,depending on the mode.

# Modes in file
#1. read(r):This mode opens the file for reading only and gives an error if the file does not exist.This is the default mode if no mode is passed as a parameter.
#2. write(w):This mode opens the file for writing only and creates a new file if the file does not exist.
#3. append(a):This mode opens the file for appending only and creates a new file if the file does not exist.
#4. create(x):This mode creates a file and gives an error if the file already exists.
#5. text(t):Apart from these modes we also need to specify how the file must be handled.t mode is used to handle text files.t refers to the text mode.
#There is no difference between r and rt or w and wt since text mode is default.
#6. binary(b): used to handle binary files (images,pdfs,etc.)

# reading the contents of the file
text = f.read()
print(text)
f.close() # closing the file

# the contents of the file will not be printed if we open it in write mode

# writing to a file
f=open('myfile.txt','w')
f.write('Hello World')
f.close()

# writing a file will overwrite its contents.
#If you want to append a file instead of overwriting it,you can open it in append mode.
f= open('myfile.txt','a')
f.write('Hello World')
f.close()

#the with statement,here no need to close the file.
#as it gets closed automatically after we are done with it.
with open('myfile.txt','r')as f:
  #do something

# Methods used in file handling.
# 1. readline() : This method reads a single line from the file.If we want to read multiple lines,we can use a loop.
f=open('myfile.txt','r') #the line by line the whole file.
while(True):
  line=f.readline()
  if not line:
    break
  print(line)
f.close()
# similarly there is readlines() method,which reads all the lines of the file and returns them as a list of strings.

# 2. writeline() : This method writes a sequence of strings to a file.The sequence can be any iterable object,such as a list or a tuple.
f=open('myfile.txt','w')
lines=['line 1\n','line 2\n','line 3\n']
f.writelines(lines)
f.close()
#writelines method does not add newline characters between the strings in the sequence.if newlines are needed ,we can use a loop to write each string separately.
#by using wrtie method.
f=open('myfile.txt','w')
lines=['line1','line2','line3']
for line in lines:
  f.write(line+'\n')
f.close()

# seek() and tell() functions: These functions are used to work with file objects and their positions within a file.These functions are a part of the built-in io
# module,which provides a consistent interface for reading and writing to various file-like objects,such as files,pipes,and in-memory buffers.

# seek() function: This function allows us to move the current position within a file to a specific point. The position is specified in bytes, and you can move either
# forward or backward from the current position.
with open('file.txt','r') as f:
  #move to the 10th byte in the file
  f.seek(10)
  #read the next 5 bytes
  data=f.read(5)
  print(data)

# tell() function: This function returns the current position within the file,in bytes.This can be useful for keeping track of your location within the file or for
# seeking to a specific position relative to the current position.
with open('file.txt','r') as f:
  #move to the 10th byte in the file
  f.seek(10)
  #save the current position
  current_position=f.tell()
  # seek to the saved position
  f.seek(current_position+5)
  #read the next 5 bytes
  data=f.read(5)
  print(data)

# truncate() function: truncates the file to a specific size.
with open('sample.txt','w') as f:
  f.write('This is a sample file')
  #truncate the file to 10 bytes
  f.truncate(10) # now the file will just have 10 bytes only.
with open('sample.txt','r') as f:
 print(f.read())