# -*- coding: utf-8 -*-
"""Function_caching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6MTBWt129p4ZuM4G0MiGPcVa6aONWWf

It is a technique for improving the performance of a program by storing the results of a function call so that you can reuse the results instead of recomputing them every time the function is called.This can be particularly useful when a function is computationally expensive,or when the inputs to the function are unlikely to change frequently.

In Python,function caching can be achieved using the functools.lru_cache decorator.It is used to cache the results of a function so that you can reuse the results instead of recomputing them everytime the function is called.
"""

# Example
import functools

@functools.lru_cache(maxsize=None)
def fibonacci(n):
    if n < 2:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(20))
# We can see memoization here.(Fetching the value from cache is memoization).
#Used when some limited values are there on which we need to run the function.
# LRU cache is refreshed once the program is over.On running the program again
#,all the computations are done again as nothing is stored in the cache anymore,