# -*- coding: utf-8 -*-
"""Generators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiStWSBjMx7Rsq7noJsYCrXuqMd7IcbY

Generators in Python are special type of functions that allow you to create an iterable sequence of values.A generator function returns a generator object,which can be used to generate the values one-by-one as you iterate over it.Generators are a powerful tool for working with large or complex data sets,as they allow you to generate the values on-the-fly,rather than having to create and store the entire sequence in memory.

**Creating a Generator**

In Python,you can create a generator by using the yield statement in a function.The yield statement returns a value from the generator and suspends the execution of the function ubtil the next value is requested.
"""

# Creating a Generator,it is used to save memory by generating values on the fly.
def my_generator():
  for i in range(5000000000): # no need to store this many values,just as many values are generated as much time next function is called
    yield i

# Using a Generator
gen = my_generator()
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen))
print(next(gen)) # only getting the value if we are applying the next function on it.