# -*- coding: utf-8 -*-
"""is vs "==".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7GXYeW_RQvJdj7JsVY1QvhAhQV4NwzY
"""

# is compares exact location of object in the memory and
# "==" compares the values of the objects

a=[1,2,43]
b=[1,2,43]
print(a is b) # false as both lists are stored at different memory locations.
print(a==b) # True as both lists have same values.

# but when we are making a constatnt then even on using different variables it points to the same memory location.
a=3
b=3 #works for strings,tuples and None as a value as well
print(a is b)
print(a==b)