# -*- coding: utf-8 -*-
"""KBC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dOfqqToatZsTS9boKX5JAxCBjC0PZvm
"""

#Making KBC game
print("Welcome to KBC")
print("So let's begin!!")
name=input("Enter your name")
print("Hello ",name)
choice=input("Do you want to begin? yes/no ")
if(choice=="yes"):
  print("let's begin with question number 1")
  question=(input(["What is capital of India? Delhi""Delhi","Mumbai","Pune","Indore"]))
  if(question=="Delhi"):
    print("Correct answer")
  else:
    print("Wrong answer")
  choice=input("Do you want to continue? yes/no ")
  if(choice=="no"):
    print("Thanks for playing")
  else:
    print("let's begin with question number 2")
    question=(input(["How is PM of India? ","modi","yogi","rahul","sonia"]))
    if(question=="modi"):
       print("Correct answer")
    else:
      print("Wrong answer")

