# -*- coding: utf-8 -*-
"""Lambada_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSGQFppnyA_DqKvK7F8vomuTtLgNihHP
"""

# A lambda funcion is a small annoymous function without a name.It is defined using the lambda keyword and has the following syntax:
lambda arguments:expression

#Lambda functions are often used in situations where a small function is required for a short period of time.
#They are commonly used as arguments to higher-order functions,such as map,filter,and reduce.
lambda x:x*2 # lambda function to double the input

# Lambda function is used where we want to pass a function as a parameter to another function.
def app(fx,value):
  return 6+fx(value)
cube=lambda x:x*x*x
print(app(lambda x:x*x,2))# we can use a function without even naming it

# Map,Filter and Reduce
# In Python,the map,filter,and reduce functions are built-in functions that allow you to apply a function to a sequence of elements and return a new sequence.These
#functions are known as higher-order functions, as they take other functions as arguments.

#map
#The map function applies a function to each element in a sequence and returns a new sequence containing the transfromed elements.
#The map function has the foloowing syntax:
map(function,iterable)
# The function argument is a function that applied to each element in the iterable argument.The iterable argument can be a list,tuple,or any other iterable object.
#Here is an example of how to use the map function:
# List of numbers
numbers=[1,2,3,4,5]
# Double each number using the map function
doubled=map(lambda x:x*2,numbers)

#filter
#The filter function filters a sequence of elements based on a given predicate(a function that returns a boolean value) and returns a new sequence containing only the
# elements that meet the predicate.The filter function has the following syntax:
filter(predicate,iterable)
# The predicate argument is a function that returns a boolean value and is applied to each element in the iterable argument.The iterable argument can be a list,tuple,
# or any other iterable object.

# filter function
l=[1,2,3,4,5,6,7,8,9,10,11,12,16]
def filter_function(a):
  return a>4 # will give all those elements which are greater than 4 in the given list.
newl=list(filter(filter_function,l))
print(newl)

#reduce
# the function argument is a function that takes in two arguments and returns a single value.The iterable argument is a sequence of elements,such as a list or a tuple.
# The reduce function applies the function to the first two elements in the iterable and then applies the function to the result and the next element and so on.
# The reduce function returns the final result.
#code:
from functools import reduce
#list of numbers
numbers=[1,2,3,4,5]
#calculate the sum of all numbers using the reduce function
product=reduce(lambda x,y:x+y,numbers)
print(product)