# -*- coding: utf-8 -*-
"""Local_VS_Global_Variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LbfP-shiK28yn0pPA7Hv6ncYnIZDtQK
"""

# Local Variable
# It is variable that is defined within a function and is only accessible
#within that function.It is created when the function is called and is destroyed
#when the function returns.

#Global Variable
#It is a varibale that is defined outside of a function and is accessible from
#within any function in your code.

x=10 #global variable
def my_function():
  y=5 #local variable
  print(y)
  global x
  x=4 #changing the value of global variable x.



my_function()
print(x)
#print(y)#this will give error as y is a local variable.

#It is generally considered good practice to avoid modifying global variables
#from within functions,as it can lead to unexpected behavior and make your
#code harder to debug.