# -*- coding: utf-8 -*-
"""Multithreading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181MVqvJ18y27_KwciIW4HGyk0n2lNBOa

**Multithreading**

Used when we want to do something or share the resources parallely.
It is a technique in programming that allows multiple threads of execution to run concurrently in a single process.But GIL (Global Interpreter Lock) doesn't allows true multithreading (parallel processing) for CPU Bound processes.But, works fine with I/O bound process.
"""

#importing the module
import threading

"""**Creating the thread**

To create a thread,we need to create a thread object and then call it's start method
"""

import threading
import time

def task(name):
    print(f"Thread {name}: Starting")
    time.sleep(2) # Simulate some work
    print(f"Thread {name}: Finishing")

print("Main thread: Before creating threads")

# Create two threads
thread1 = threading.Thread(target=task, args=("One",))
thread2 = threading.Thread(target=task, args=("Two",))

# Start the threads
thread1.start()
thread2.start()

# Wait for both threads to complete
thread1.join()
thread2.join()

print("Main thread: All threads finished")

import threading
import time

def heavy_task():
    # A simple task to consume some time
    count = 0
    for i in range(10**7):
        count += i

# 1. Normal (Sequential) Execution
start_time = time.time()
print("Starting Sequential Execution...")
for _ in range(4):
    heavy_task()
end_time = time.time()
sequential_time = end_time - start_time
print(f"Sequential Execution took: {sequential_time:.2f} seconds\n")

# 2. Multithreaded Execution
threads = []
start_time = time.time()
print("Starting Multithreaded Execution...")
for _ in range(4):
    t = threading.Thread(target=heavy_task)
    threads.append(t)
    t.start()

for t in threads:
    t.join()

end_time = time.time()
threaded_time = end_time - start_time
print(f"Multithreaded Execution took: {threaded_time:.2f} seconds")