# -*- coding: utf-8 -*-
"""OS_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U00XD7cR8S08QrpC6axb-qa82cE4kJVA

OS module is a built-in module that provides functions for interacting with the operating system. It allows to perform a wide variety of tasks,such as reading and writing files,interacting with the file system,and running system commands.
"""

# Here are some common tasks performed with the os module:
# Reading and writing files,the OS module provides functions for
#opening,reading,and writing files.

#For example,to open a file for reading,you can use the open function:
import os
#open the file in read-only mode
f=os.open("myfile.txt",os.O_RDONLY)
#read the contents of the file
contents=os.read(f,1024)
#close the file
os.close(f)

# To open a file for writing
f=os.open("myfile.txt",os.O_WRONLY)
#write some data to the file
os.write(f,"Hello,world!")
#close the file
os.close(f)

# for making a directory
os.mkdir("mydir")
#for renaming a directory
os.rename("mydir","newdir") #rename(old_name,new_name)
#for removing a directory
os.rmdir("newdir")

# for seeing a list of folders inside a directory
f=os.listdir("folder_name")
print(f)

# for seeing files under a directories sub directory
for folder in folders:
  print(folder)
  print(os.listdir(f"data/{folder}")) # main dir=data under which folders
                                      #and we are finding if any file
                                      #under folders.

# we can os.system to run any command

# for getting current working directory
print(os.getcwd())
#for changing the current working directory
os.chdir("new_dir")
#for printing the changed directory
print(os.getcwd())

# removing operations
os.remove("myfile.txt") # removes a file
os.rmdir("mydir") # removes an empty directory
shutil.rmtree("mydir") # removes a directory and all its contents
#shutil module is somewhere mostly similar to os module.

