# -*- coding: utf-8 -*-
"""Regular_Expression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2xVCUAEc6w8EseHP8S0gLSn2m0vRTeY

**Regular Expression**

Aka "regex" for short,are a powerful tool for working with strings and text data in Python.They allow you to match and manipulate strings based on patterns,making it easy to perform complex string operations with just a few lines of code.

**Metacharacters in regular expressions**

[]: Represent a character class

^ : Matches the beginning

$ : Matches the end

. : Matches any character except newline

? : Matches zero or one occurence

| : Means OR (Matches with any of the characters separated by it)

* : Any number of occurences

+ : One or more occurences

{} : Indicate number of occurences of a preceding RE to match.

() : Enclose a group of REs.
"""

import re # re module for regular expressions
pattern = "H"
text = " Hello! How are you ?.you are from Indore or Bhopal?"
re.findall(pattern,text) # finding number of times a specific pattern occurs