# -*- coding: utf-8 -*-
"""shutil_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIxJaB-rwli2QCFxAhsCZQV6kSa3vlfb

**Shutil_module**

It is a python module that provides a higher level interface for working with file and directories.The name shutil is short form for shell utility.It provides an efficient and convenient way to automate tasks that are commonly performed on files and directories.
"""

#importing shutil
import shutil

"""functions in shutil
1. shutil.copy(src,dest) : This function copies the file from specified source file to the destination file.If the destination file exists ot overwrites it.
2. shutil.copy2(src,dest) : This is similar to copy function but,it also perserves the metadata about the original file such as timestamp.
3. shutil.copytree(src,dest) : This function recursively copies the directory located at src to the new location specified by dest.If destination location already exists,the original directory will be merged with it
4. shutil.move(src,dest) : This function moves the file located at src to a new location specified by dst.This function is equivalent to renaming a file in most cases.
5. shutil.rmtree(path) : This function recursively deletes the directory located at the path ,along with all of its contents.This function is similar to using the rm -rf in a shell.
"""