# -*- coding: utf-8 -*-
"""Snake,Water and Gun

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTWt5JuCXAkFR-MJa15cDXU7VVLcvThZ
"""

print("Welcome to the game of Snake,Water and Gun: S for Snake, W for Water and G for Gun")
a=input("Enter input for player-1 :")
b=input("Enter input for player-2 :")
if (a=="S" and b=="W") or (a=="W" and b=="G") or (a=="G" and b=="S"):
    print("Player-1 wins")
elif (a=="W" and b=="S") or (a=="G" and b=="W") or (a=="S" and b=="G"):
    print("Player-2 wins")
else:
    print("Draw")