# -*- coding: utf-8 -*-
"""Time_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uBi_QnewNgvP20ZOaw_Un8u1bUZKJRv

**Time Module**

The time module in Python provides a set of functions to work with time-related operations,such as timekeeping,formatting,and time conversions.This module is part of the Python Standard Library and is available in all Python installations,making it a convenient and essential tool for a wide range of applications.

1. time.time()
This function returns tthe current time as floating point number,representing the number of seconds since the unix epoch (the point in time when the time module was initialized): jan 1,1970 00:00:00.The returned value is based on the computer system's clock and is affected by time adjustments made by the operating system,such as daylight saving time.
"""

# example
import time
print(time.time())

"""2. time.sleep()
This function makes the compiler wait for specifed seconds before executing the next line of code.The specified seconds can also have decimal values for more precision.
"""

#example
print("Hi")
time.sleep(3.85)
print("This line printed after 3.85 seconds")

"""3. time.strftime()
This function formats a time value as a string,based on a specified format.This function is particularly useful for formatting dates and times in a human-readable format,suzh as for display in a GUI,a log file,or a report.
"""

#example
t=time.localtime()
formatted_time=time.strftime(" %Y-%m-%d ,%H:%M:%S",t)
print(formatted_time)