# -*- coding: utf-8 -*-
"""Virtual_Environment_in_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkBu4mxmPXAhOQWg0_7pqPG9vKoVp0s3
"""

# Virtual Environment can used as a isolated platform for maintaing the code's
# maintainiabilty by ensuring the same version of python runs on every machine related to
# particular project.
#Can be used as measure for version control and we can install packages according
# to our needs.

# Virtual environment is a tool used to isolate specific python environments on a single
#machine,allowing you to work on multiple projects with different dependencies
#and packages.

#this can be especially useful when working on projects that have conflicting
#packaging versions or packages that are not compatible with each other.

# creating a virtual environment
python -M venv myenv

# Activating the virtual environment
myenv\Scripts\activate

# for installing a particular version of any package in the virtual environment
pip install pandas==1.4.4 #version name

# writing simply deactivate to deactive the current virtual environment
deactivate

# for windows activating a virtual environment
myenv\Scripts\activate.bat

# the requirements.txt file
#In addition to creating and activating a virtual environment,it can be useful to
#create a requirements.txt file that lists the packages and their versions taht
# your project depends on. This file can be used to easily install all the
#required packages in a new environment.

# to create a requirements.txt file,you can use the pip freeze command,which
#outputs a list of installed packages and their versions.

#output the list of installed packages and their versions to a file
pip freeze > requirements.txt
# to install the packages listed in the requirements.txt file
pip install -r requirements.txt
# just to see the packages installed in the virtual environment
pip freeze