# -*- coding: utf-8 -*-
"""Walrus_Operator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUaW3pVGDIzNnpKbEs6Y41rw9LUg0rGF

**Walrus Operator**

It is a new addition in Python 3.8 onwards and allows us to assign a value to a variable within an expression.This can be useful when you need to use a value multiple times in a loop,but don't want to repeat the calculation.
It is represented as :=
"""

#Example
numbers=[1,2,3,4,5]
while (n:= len(numbers))>0:
  print(numbers.pop())

#Walrus with if condition
names=["JIM","KIM","HAM"]

if (name:=input("Enter a name"))in names:
  print (f"Hello {name}!")
else:
         print("Name not found")