# -*- coding: utf-8 -*-
"""working_of_import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oqt93Tsgd87B3gicl1jHQBmeySTpgZ0
"""

#Import in Python
# Importing in python is the process of loading code from a pyhton module into
#the curent script.This allows us to use the functions and variables defined in
#the module in your current script,as well as any modules that the imported
#module may depend on.
# To import a module in python,we use the import statment followed by the name
#of the module.

import math #importing math module
result=math.sqrt(9) #dot notation is used for implementing any module's function
print(result)

math.floor(12.365849687897)

# from keyword
from math import sqrt,pi
result=sqrt(9)
print(result)
print(pi)

#importing everything
# it is also possible to import all functions from a module using the * wildcard.
#However,this is generally not recommended as it can lead to confusion and make it
# harder to understand where specific functions and variables are coming from.

from math import *
result= sqrt(9)
print(result)
print(pi)

# as keyword
#It is useful in creating a short name for the module which is easy to use.
import pandas as pd

# dir function
#It is a built-in function called dir that you can use to view the names of all
#the functions and variables defined in a module.This can be helpful for
#exploring and understanding the contents of a new module.
import math
print(dir(math))

# Similarly.we can import the other python files made by us in another program
import file_name # 1 way
from file_name import *